# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    # Use the custom Maven build action
    - name: Build with Maven (Custom Action)
      uses: andrejcoliveira18/ACADEMY_CICD/.github/actions/maven_build@main

    - name: Create new Docker image
      run: docker build . --file ./src/main/docker/Dockerfile.jvm --tag academy:$(date +%s)

    - name: List Docker images
      run: docker images
